import { useEffect, useState } from 'react'
import { GlassPanel, SectionEyebrow, KeyTakeaway } from '../ui/GlassPanel'

interface MallRow {
  mall_id: string
  mall?: string
  visitors?: number
  visitor_sessions?: number
  med_dwell_min?: number
  grab_share?: number
  browse_share?: number
  day_out_share?: number
}

interface MallReport {
  status?: string
  reason?: string
  resolution_policy?: {
    default: string
    store_footfall: string
    floor_shares: string
    note: string
  }
  sessions?: {
    totals?: Record<string, number>
    by_mall?: MallRow[]
  }
  abstention?: Array<{
    action: string
    emit_level: string
    stops: number
    mean_entropy: number
    mean_margin: number
  }>
  overlap?: Array<{
    mall_a: string
    mall_b: string
    shared_devices: number
    overlap_share: number
  }>
  weighted_vs_unweighted?: {
    counter_status?: { status: string; note: string }
  }
  suppressed?: string[]
}

export function MallIntelligencePanel() {
  const [data, setData] = useState<MallReport | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const url = new URL(`${import.meta.env.BASE_URL}demo/mall.json`, window.location.href).href
    fetch(url)
      .then((r) => {
        if (!r.ok) throw new Error('mall.json not found — run mall insights export')
        return r.json()
      })
      .then((j) => setData(j))
      .catch((e) => setError(String(e)))
  }, [])

  if (error) {
    return (
      <GlassPanel className="p-6">
        <SectionEyebrow>Mall intelligence</SectionEyebrow>
        <p className="mt-2 text-sm text-[var(--vm-muted)]">
          Mall campus metrics are generated by the shadow pipeline. Export with{' '}
          <code className="text-teal-300">python3 -m analytics insights --only mall</code> and copy
          to <code className="text-teal-300">public/demo/mall.json</code>.
        </p>
        <p className="mt-2 text-xs text-rose-300/80">{error}</p>
      </GlassPanel>
    )
  }

  if (!data) {
    return (
      <GlassPanel className="p-8 text-center text-[var(--vm-muted)]">Loading mall metrics…</GlassPanel>
    )
  }

  if (data.status === 'skipped') {
    return (
      <GlassPanel className="p-6">
        <SectionEyebrow>Mall intelligence</SectionEyebrow>
        <p className="mt-2 text-sm text-[var(--vm-muted)]">{data.reason}</p>
      </GlassPanel>
    )
  }

  const malls = data.sessions?.by_mall ?? []
  const totals = data.sessions?.totals
  const abstention = data.abstention ?? []

  return (
    <div className="space-y-5">
      <GlassPanel variant="bright" className="p-6 lg:p-8">
        <SectionEyebrow>Uncertainty-aware mall model · June pilots</SectionEyebrow>
        <h2 className="mt-2 font-display text-3xl text-white">Campus & zone intelligence</h2>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--vm-muted)]">
          Default resolution is mall and zone. Store and floor claims stay suppressed until verified
          journeys and calibration gates pass. Geometry is provisional public campus polygons for
          Waterway Point, JEM, and VivoCity.
        </p>
        {data.resolution_policy && (
          <div className="mt-4">
            <KeyTakeaway>
              Policy: <strong className="text-white">{data.resolution_policy.default}</strong> —{' '}
              {data.resolution_policy.store_footfall.replaceAll('_', ' ')}.
            </KeyTakeaway>
          </div>
        )}
        {totals && (
          <div className="mt-6 grid gap-3 sm:grid-cols-3">
            <Stat label="Visitor sessions" value={fmt(totals.visitor_sessions)} />
            <Stat label="Visitor devices" value={fmt(totals.visitor_devices)} />
            <Stat label="Median dwell (min)" value={String(totals.med_dwell_min ?? '—')} />
          </div>
        )}
      </GlassPanel>

      <div className="grid gap-5 lg:grid-cols-2">
        <GlassPanel className="p-5">
          <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[var(--vm-muted)]">
            Pilot malls (visitor)
          </p>
          <div className="mt-3 space-y-2">
            {malls.map((m) => (
              <div
                key={m.mall_id}
                className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3"
              >
                <div>
                  <p className="font-medium text-white">{m.mall ?? m.mall_id}</p>
                  <p className="text-xs text-[var(--vm-muted)]">
                    med dwell {m.med_dwell_min ?? '—'} min · browse{' '}
                    {pct(m.browse_share)} · day-out {pct(m.day_out_share)}
                  </p>
                </div>
                <p className="font-mono text-lg text-teal-300">{fmt(m.visitors)}</p>
              </div>
            ))}
            {!malls.length && (
              <p className="text-sm text-[var(--vm-muted)]">No mall rows yet.</p>
            )}
          </div>
        </GlassPanel>

        <GlassPanel className="p-5">
          <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[var(--vm-muted)]">
            Abstention mix
          </p>
          <div className="mt-3 space-y-2">
            {abstention.map((a) => (
              <div
                key={`${a.action}-${a.emit_level}`}
                className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3"
              >
                <div className="flex items-center justify-between">
                  <p className="font-medium text-white">{a.action}</p>
                  <p className="font-mono text-teal-300">{fmt(a.stops)}</p>
                </div>
                <p className="mt-1 text-xs text-[var(--vm-muted)]">
                  emit {a.emit_level} · entropy {a.mean_entropy} · margin {a.mean_margin}
                </p>
              </div>
            ))}
          </div>
          {data.weighted_vs_unweighted?.counter_status && (
            <p className="mt-4 text-xs text-amber-200/80">
              Counters: {data.weighted_vs_unweighted.counter_status.status.replaceAll('_', ' ')}.
            </p>
          )}
        </GlassPanel>
      </div>

      <GlassPanel className="p-4">
        <p className="text-[11px] text-[var(--vm-muted)]">
          Suppressed from default product: {(data.suppressed ?? []).join(', ') || 'none'}. June
          evaluates coverage, uncertainty, topology, and abstention — not true store/floor accuracy.
        </p>
      </GlassPanel>
    </div>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-white/[0.06] bg-black/20 p-4">
      <p className="text-xs text-[var(--vm-muted)]">{label}</p>
      <p className="mt-1 font-mono text-xl text-white">{value}</p>
    </div>
  )
}

function fmt(n?: number) {
  if (n == null) return '—'
  return n.toLocaleString()
}

function pct(n?: number) {
  if (n == null) return '—'
  return `${Math.round(n * 100)}%`
}
