import type { MallProfile } from '../types'
import { TEAL, TEAL_MID, DEEP, SES_RAMP } from '../palette'

// JEM — transit-anchored town-centre mall (Jurong East). Observed figures from
// the July 2026 Veraset bundle; indoor Wi-Fi hotspots are illustrative.
export const jem: MallProfile = {
  id: 'jem',
  name: 'Jem',
  archetype: 'Transit town-centre',
  tagline: 'from catchment to corridor',
  blurb: 'A real July 2026 mobility read of Jem, joined to its public floor plan—then extended into the zone-level decisions mall Wi‑Fi could unlock.',
  address: '50 Jurong Gateway Rd',
  planKind: 'official',
  planLabel: 'Official Jem plan',
  planSourceLabel: 'Floor-plan source · Jem accessibility guide',
  planSourceUrl: 'https://www.jem.sg/accessibility-guide/',

  kpis: [
    { label: 'Observed devices', value: '12,562', detail: 'July panel, not total visitors' },
    { label: 'Median dwell', value: '64.1 min', detail: '95% CI · 62.5–65.9' },
    { label: 'Repeat rate', value: '31.4%', detail: '95% CI · 28.8–34.2' },
    { label: 'Home within 3 km', value: '29.2%', detail: 'median home distance · 5.0 km' },
  ],
  meanDaily: '764',
  trend: [95.4,108.9,134,104.6,94.8,90.7,93.7,92.6,100.8,139.3,109.1,93.3,72.8,77.1,78.6,92.8,128.2,99.5,86.1,75.1,87.3,88.3,99.1,132.6,106.1,94,83.3,99.6,84.5,105.5,152.3],
  trendPeak: { index: 30, value: 152 },
  panelSensitive: true,

  mission: [
    { label: 'Browse', value: 49.6, note: 'multi-stop shopping pattern', color: TEAL },
    { label: 'Day out', value: 35.6, note: 'longer, broader activity pattern', color: TEAL_MID },
    { label: 'Grab & go', value: 14.9, note: 'short, focused visit pattern', color: DEEP },
  ],
  missionFacts: [
    { label: 'Near-transit share', value: '26.9%' },
    { label: 'Top behavioral peer', value: 'NEX · 0.56' },
  ],

  catchment: {
    bands: [
      { km: 2, label: '2 km', uw: 14.1, w: 11.0 },
      { km: 3, label: '3 km', uw: 29.2, w: 26.4 },
      { km: 5, label: '5 km', uw: 50.5, w: 48.4 },
      { km: 10, label: '10 km', uw: 75.9, w: 74.8 },
    ],
    medHome: '4.96 km', weightedVisitors: '19,921', ess: '18,942', markKm: 3, markLabel: '3 km · 26%',
  },
  rhythm: {
    weekday: [1.2,0.7,0.7,0.4,0.5,2.0,10.1,18.4,45.7,42.9,43.2,56.3,72.5,61.7,53.3,48.6,49.2,63.3,84.8,63.8,39.5,15.4,6.2,3.1],
    weekend: [1.1,0,0,0,0,1.8,8.6,13.6,38.1,48.0,65.6,68.3,89.8,88.9,77.1,75.0,74.6,80.3,81.4,67.6,50.0,18.4,6.4,2.4],
    weekdayPeakH: 18, weekendPeakH: 12,
    weekdayNote: 'Weekday · peaks 18:00', weekendNote: 'Weekend · peaks 12:00',
  },

  sesAuc: '0.69',
  ses: [
    { label: 'Q1', value: 16, tone: SES_RAMP[0], detail: 'lower propensity' },
    { label: 'Q2', value: 23, tone: SES_RAMP[1], detail: '' },
    { label: 'Q3', value: 29, tone: SES_RAMP[2], detail: 'largest cohort' },
    { label: 'Q4', value: 20, tone: SES_RAMP[3], detail: '' },
    { label: 'Q5', value: 12, tone: SES_RAMP[4], detail: 'higher propensity' },
  ],
  sesFacts: [
    { label: 'Jurong West', value: 'Q3 · 38% Q4/5' },
    { label: 'Clementi', value: 'Q3 · 39% Q4/5' },
    { label: 'Bukit Batok', value: 'Q3 · 34% Q4/5' },
  ],
  behaviorHeadline: 'A balanced local, student and commuter asset',
  behavior: [
    { label: 'Local resident', value: 23.9, note: '2.00 legs · 19% multi-stop' },
    { label: 'School-linked', value: 22.0, note: '2.13 legs · 23% multi-stop' },
    { label: 'Town commuter', value: 21.6, note: '2.25 legs · 29% multi-stop' },
    { label: 'Works near home', value: 12.0, note: '2.33 legs · 31% multi-stop' },
    { label: 'Long-haul commuter', value: 8.0, note: '2.43 legs · 33% multi-stop' },
    { label: 'Other', value: 12.5, note: 'remaining July segments' },
  ],
  tripChains: [
    { label: 'Local errand loop', share: '24%', segment: 'Local resident', stops: ['Home', 'Jem', 'Grocery / service', 'Home'] },
    { label: 'School-linked stop', share: '22%', segment: 'School-linked', stops: ['School', 'Jem', 'MRT / bus', 'Home'] },
    { label: 'Commute interchange', share: '21%', segment: 'Town commuter', stops: ['Home', 'Jurong East MRT', 'Jem', 'Work'] },
    { label: 'Workday extension', share: '12%', segment: 'Works near home', stops: ['Work', 'Jem lunch', 'Work', 'Home'] },
  ],

  crossShop: [
    { mall: 'Jurong Point', share: 22.1, shared: 2291 },
    { mall: 'VivoCity', share: 13.7, shared: 1684 },
    { mall: 'Bugis Junction', share: 12.5, shared: 1576 },
    { mall: 'Causeway Point', share: 11.8, shared: 1229 },
    { mall: 'Plaza Singapura', share: 11.0, shared: 992 },
    { mall: 'Ngee Ann City', share: 9.4, shared: 1180 },
    { mall: 'ION Orchard', share: 9.4, shared: 1184 },
    { mall: 'Suntec City', share: 8.8, shared: 873 },
    { mall: 'Northpoint City', share: 7.8, shared: 984 },
    { mall: 'Jewel Changi', share: 7.2, shared: 824 },
  ],
  peers: [
    { mall: 'NEX', sim: 0.558 },
    { mall: 'Bugis Junction', sim: 0.486 },
    { mall: 'Tampines Mall', sim: 0.481 },
    { mall: 'VivoCity', sim: 0.457 },
    { mall: 'Jurong Point', sim: 0.441 },
  ],
  peersNote: 'NEX is Jem’s closest behavioral peer yet only 5% of visitors overlap.',
  drift: {
    significant: true,
    headline: 'Who the audience shifted toward',
    segments: [
      { segment: 'School-linked', delta: 12.0 },
      { segment: 'Works near home', delta: 2.1 },
      { segment: 'Homebody', delta: -3.5 },
      { segment: 'Local resident', delta: -5.3 },
      { segment: 'Town commuter', delta: -7.1 },
    ],
    embedding: '0.116', embeddingCi: '1 − cosine · CI 0.112–0.119', matched: '0.133', newVisitor: '85.3%',
    window: 'June covers 7 days and July covers 31 days, with high panel turnover.',
  },

  floors: ['L1', 'L2'],
  floorLabel: (f) => (f === 'L1' ? 'Level 1' : 'Level 2'),
  defaultFloor: 'L2',
  defaultZoneId: (f) => (f === 'L1' ? 'l1-core-mid' : 'l2-mrt'),
  hotspots: {
    L1: [
      { id: 'l1-entry-a', name: 'Entry A threshold', context: 'North arrival sensor cell', x: 48, y: 26, presence: 62, dwell: 5, capture: 43, change: 5.1, opportunity: 'Separate true entries from pedestrians circulating along Jem Street.' },
      { id: 'l1-jem-street', name: 'Jem Street promenade', context: 'Outdoor F&B frontage', x: 58, y: 31, presence: 71, dwell: 19, capture: 39, change: 6.4, opportunity: 'Compare outdoor dwell with subsequent indoor capture by weather and event schedule.' },
      { id: 'l1-mcd', name: 'McDonald’s frontage', context: 'North-east F&B cluster', x: 72, y: 35, presence: 59, dwell: 24, capture: 36, change: 3.5, opportunity: 'Measure whether F&B dwell creates onward retail visits or remains a single-stop mission.' },
      { id: 'l1-entry-b', name: 'Entry B threshold', context: 'North-west approach', x: 23, y: 39, presence: 74, dwell: 4, capture: 58, change: 7.8, opportunity: 'Benchmark arrival conversion against adjacent Entry C.' },
      { id: 'l1-entry-c', name: 'Entry C threshold', context: 'Westgate-facing approach', x: 18, y: 52, presence: 94, dwell: 5, capture: 67, change: 9.2, opportunity: 'Sequence messaging for the highest-volume Westgate transfer cohort.' },
      { id: 'l1-hm', name: 'H&M frontage', context: 'West anchor shopfront', x: 31, y: 45, presence: 86, dwell: 16, capture: 61, change: 6.8, opportunity: 'Quantify storefront exposure, entry and post-visit paths separately.' },
      { id: 'l1-north-core', name: 'North spine junction', context: 'First major route choice', x: 48, y: 43, presence: 81, dwell: 11, capture: 54, change: 2.7, opportunity: 'Identify the first route choice after north and west arrivals.' },
      { id: 'l1-lift-1', name: 'Lift Lobby 1', context: 'Vertical circulation cell', x: 59, y: 47, presence: 66, dwell: 9, capture: 48, change: -1.1, opportunity: 'Measure queueing and the floors reached after lift use.' },
      { id: 'l1-core-west', name: 'Central spine west', context: 'Main circulation corridor', x: 39, y: 58, presence: 89, dwell: 14, capture: 64, change: 4.9, opportunity: 'Test whether activations improve stopping without obstructing flow.' },
      { id: 'l1-core-mid', name: 'Central spine middle', context: 'Atrium and escalator approach', x: 52, y: 58, presence: 97, dwell: 22, capture: 69, change: 8.1, opportunity: 'Score atrium programming against dwell and onward visitation.' },
      { id: 'l1-core-east', name: 'Central spine east', context: 'Eastward retail circulation', x: 67, y: 58, presence: 72, dwell: 13, capture: 51, change: -2.2, opportunity: 'Locate the exact point where eastbound circulation drops.' },
      { id: 'l1-lift-2', name: 'Lift Lobby 2', context: 'East vertical circulation', x: 77, y: 55, presence: 48, dwell: 8, capture: 45, change: 1.6, opportunity: 'Compare floor-change demand with the west lift lobby.' },
      { id: 'l1-jewel-west', name: 'Jewellery arc west', context: 'Premium retail cluster', x: 37, y: 72, presence: 57, dwell: 25, capture: 36, change: -3.9, opportunity: 'Measure cross-shopping across adjacent premium storefronts.' },
      { id: 'l1-jewel-mid', name: 'Jewellery arc centre', context: 'Curved south retail run', x: 51, y: 78, presence: 63, dwell: 31, capture: 41, change: 4.4, opportunity: 'Distinguish window engagement from store-entry conversion.' },
      { id: 'l1-jewel-east', name: 'Jewellery arc east', context: 'South-east category edge', x: 65, y: 76, presence: 49, dwell: 21, capture: 31, change: -5.4, opportunity: 'Diagnose category-cluster leakage into the east wing.' },
      { id: 'l1-entry-d', name: 'Entry D / taxi stand', context: 'Pick-up and drop-off threshold', x: 19, y: 83, presence: 51, dwell: 6, capture: 74, change: 11.6, opportunity: 'Link arrival mode to first-zone choice and total mall dwell.' },
      { id: 'l1-south-east', name: 'South-east retail pocket', context: 'Lower-volume tenant cluster', x: 76, y: 83, presence: 42, dwell: 18, capture: 29, change: -6.8, opportunity: 'Find whether low capture is caused by route visibility or tenant appeal.' },
      { id: 'l1-entry-e', name: 'Entry E threshold', context: 'Boon Lay Way approach', x: 87, y: 79, presence: 45, dwell: 5, capture: 49, change: -2.5, opportunity: 'Review wayfinding and sightlines on the lower-volume east approach.' },
    ],
    L2: [
      { id: 'l2-entry-f', name: 'Entry F threshold', context: 'North-west external approach', x: 31, y: 24, presence: 52, dwell: 5, capture: 42, change: 1.8, opportunity: 'Compare the north-west entrance cohort with MRT-linked arrivals.' },
      { id: 'l2-hm-north', name: 'H&M north frontage', context: 'Upper west anchor edge', x: 39, y: 31, presence: 61, dwell: 18, capture: 44, change: 2.4, opportunity: 'Measure frontage exposure before visitors enter the main spine.' },
      { id: 'l2-mrt', name: 'Entry G / MRT threshold', context: 'Direct Jurong East MRT connection', x: 12, y: 46, presence: 100, dwell: 5, capture: 78, change: 12.6, opportunity: 'Separate commuters, mall visitors and pass-through traffic with dwell rules.' },
      { id: 'l2-mrt-junction', name: 'MRT decision junction', context: 'First route choice from Entry G', x: 23, y: 47, presence: 96, dwell: 9, capture: 73, change: 10.8, opportunity: 'Quantify north, east and anchor-bound route choice after MRT arrival.' },
      { id: 'l2-hm', name: 'H&M west frontage', context: 'Units #02-01/02/03', x: 31, y: 42, presence: 69, dwell: 24, capture: 49, change: 3.2, opportunity: 'Separate storefront passers-by from shoppers entering the anchor.' },
      { id: 'l2-lift-1', name: 'Lift Lobby 1', context: 'West vertical circulation', x: 42, y: 49, presence: 58, dwell: 10, capture: 46, change: -1.6, opportunity: 'Measure queueing and floor destinations after lift use.' },
      { id: 'l2-core-west', name: 'Central spine west', context: 'Primary MRT-to-mall corridor', x: 38, y: 58, presence: 91, dwell: 13, capture: 68, change: 7.7, opportunity: 'Locate stopping and leakage along the busiest transfer corridor.' },
      { id: 'l2-core-mid', name: 'Central spine middle', context: 'Escalator and atrium zone', x: 52, y: 58, presence: 86, dwell: 18, capture: 61, change: 3.9, opportunity: 'Score escalator-adjacent campaigns against route and dwell lift.' },
      { id: 'l2-core-east', name: 'Central spine east', context: 'Anchor-bound corridor', x: 67, y: 59, presence: 79, dwell: 15, capture: 56, change: -1.4, opportunity: 'Identify where anchor-bound traffic bypasses smaller tenants.' },
      { id: 'l2-lift-2', name: 'Lift Lobby 2', context: 'East vertical circulation', x: 76, y: 52, presence: 51, dwell: 11, capture: 43, change: 2.1, opportunity: 'Compare vertical movement and queue conditions by lift bank.' },
      { id: 'l2-uniqlo', name: 'UNIQLO frontage', context: 'West anchor cluster', x: 22, y: 66, presence: 87, dwell: 34, capture: 66, change: 8.8, opportunity: 'Reveal which arrival cohorts enter this anchor and where they go next.' },
      { id: 'l2-donki', name: 'DON DON DONKI frontage', context: 'South-west anchor cluster', x: 30, y: 76, presence: 93, dwell: 42, capture: 71, change: 10.1, opportunity: 'Measure anchor halo across neighboring tenants and levels.' },
      { id: 'l2-west-south', name: 'West retail connector', context: 'Anchor-to-spine transition', x: 39, y: 70, presence: 74, dwell: 17, capture: 53, change: 4.6, opportunity: 'Quantify how anchor visitors rejoin the mall circulation network.' },
      { id: 'l2-south-row', name: 'South retail row', context: 'Specialty retail frontage', x: 51, y: 78, presence: 55, dwell: 20, capture: 38, change: -3.7, opportunity: 'Compare window dwell and entry capture across small-format tenants.' },
      { id: 'l2-ikea-west', name: 'IKEA west frontage', context: 'Approach to east anchor', x: 73, y: 69, presence: 77, dwell: 29, capture: 58, change: 5.5, opportunity: 'Identify the tenant halo before entry into IKEA.' },
      { id: 'l2-ikea', name: 'IKEA Jurong entrance', context: 'East anchor #02-12/13/14', x: 84, y: 66, presence: 83, dwell: 48, capture: 64, change: 7.2, opportunity: 'Connect anchor dwell to onward tenant visitation across Levels 2–4.' },
      { id: 'l2-east-wing', name: 'East wing connector', context: 'Secondary east circulation', x: 85, y: 79, presence: 48, dwell: 14, capture: 35, change: -4.5, opportunity: 'Diagnose route visibility and dead-zone risk around the east connector.' },
      { id: 'l2-south', name: 'Entry H / office link', context: 'Perennial Business City approach', x: 34, y: 91, presence: 49, dwell: 6, capture: 41, change: -4.8, opportunity: 'Test lunch and after-work conversion from the office-link cohort.' },
    ],
  },
  floorplan: {
    type: 'image',
    images: {
      L1: `${import.meta.env.BASE_URL}demo/mall-assets/jem-level-1-display.png`,
      L2: `${import.meta.env.BASE_URL}demo/mall-assets/jem-level-2-display.png`,
    },
    sourceUrl: {
      L1: 'https://www.jem.sg/accessibility-guide/level-1/',
      L2: 'https://www.jem.sg/accessibility-guide/level-2/',
    },
    journeys: {
      L1: ['M18 48 C32 51 43 57 55 58 S72 67 82 78', 'M18 84 C30 76 39 73 53 76 S66 69 55 58'],
      L2: ['M8 46 C24 44 30 56 48 58 S72 58 86 67', 'M8 46 C24 53 21 67 29 70 S47 67 58 61'],
    },
  },
}
